name: SmartPlant Local
values:
  - key: baseUrl
    value: 'http://localhost:8080/api'
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: usuarioId
    value: ''
    enabled: true
  - key: plantaId
    value: '1'
    enabled: true
  - key: inventarioId
    value: ''
    enabled: true
  - key: cuidadoId
    value: ''
    enabled: true
