services:
  db:
    image: postgres:16-alpine
    container_name: smartplant-db
    environment:
      POSTGRES_DB: smartplant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartplant"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: smartplant-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smartplant
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: smartplant_clave_super_segura_de_32_caracteres
      JWT_EXPIRATION_MS: 86400000
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: llama-3.3-70b-versatile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../Frontend
    container_name: smartplant-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
